# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: medrec.com
    EnableNodeOUs: true
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
      - Hostname: orderer2
      - Hostname: orderer3
      - Hostname: orderer4
      - Hostname: orderer5

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # Org1
  - Name: Org1
    Domain: org1.medrec.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  # Org2
  - Name: Org2
    Domain: org2.medrec.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  #Org3
  - Name: Org3
    Domain: org3.medrec.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1